num_units: 100
true_model:
  true_fields: uniform(-.3 * beta, .3 * beta); beta=1.5
  true_couplings: normal(0,  beta / sqrt(num_units)); symmetric, beta=1.5
  num_sims: 30000
  num_burn: 1000
inverse_methods:
  EQ:
  - nMF
  - TAP
  - ML
  NEQ: []
maximum_likelihood:
  num_steps: 3000
  learning_rate: 0.1
  is_converged: null
  num_sims: 30000
  num_burn: 1000
