num_units: 50
true_model:
  true_fields: uniform(-.3 * beta, .3 * beta); beta=1.3
  true_couplings: normal(0,  beta / sqrt(num_units)); symmetric, beta=1.3
  num_sims: 100000
  num_burn: 1000
inverse_methods:
  EQ:
  - nMF
  - TAP
  - PLLH
  - ML
  NEQ: []
maximum_likelihood:
  num_steps: 5000
  learning_rate: 0.1
  is_converged: null
  num_sims: 100000
  num_burn: 1000
